// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYRO4vW0BO4necsefhlpVgjdnQrG1O8jg',
    appId: '1:798729105172:web:2b9a0c2311075bc8549c01',
    messagingSenderId: '798729105172',
    projectId: 'homework04-4812c',
    authDomain: 'homework04-4812c.firebaseapp.com',
    storageBucket: 'homework04-4812c.firebasestorage.app',
    measurementId: 'G-LJ7402S1RE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoYcEgh0dAy0qAJpxv5btgNDkjbJOh6Gw',
    appId: '1:798729105172:android:7efd82b10c165b60549c01',
    messagingSenderId: '798729105172',
    projectId: 'homework04-4812c',
    storageBucket: 'homework04-4812c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcGNLtdVv6N8Pqi1VYh83bHo0vjEHqkgc',
    appId: '1:798729105172:ios:ead2bd46bf7cbfcc549c01',
    messagingSenderId: '798729105172',
    projectId: 'homework04-4812c',
    storageBucket: 'homework04-4812c.firebasestorage.app',
    iosBundleId: 'com.example.madHw04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcGNLtdVv6N8Pqi1VYh83bHo0vjEHqkgc',
    appId: '1:798729105172:ios:ead2bd46bf7cbfcc549c01',
    messagingSenderId: '798729105172',
    projectId: 'homework04-4812c',
    storageBucket: 'homework04-4812c.firebasestorage.app',
    iosBundleId: 'com.example.madHw04',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYRO4vW0BO4necsefhlpVgjdnQrG1O8jg',
    appId: '1:798729105172:web:f74bc4711ccf7925549c01',
    messagingSenderId: '798729105172',
    projectId: 'homework04-4812c',
    authDomain: 'homework04-4812c.firebaseapp.com',
    storageBucket: 'homework04-4812c.firebasestorage.app',
    measurementId: 'G-GQC9FRERJY',
  );
}
